"""Frozen PROJECT_V1 wire format and bounded incremental decoding.

No device command is inferred from the link type. Frames containing ``reset``
are ordinary binary frames; raw text is never generated by this adapter.
"""

from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
import secrets
import struct
import time

from .models import TelemetrySample


PROJECT_V1 = "PROJECT_V1"
HELLO, ARM, SET_PWM, STOP, SET_SPEED, GET_PARAMS, SET_PARAMS = range(1, 8)
CAPS, ACK, STATE, PARAMS = range(0x81, 0x85)
HEADER = struct.Struct("<2sBBHII")
CAPS_LAYOUT = struct.Struct("<HHHHHHB")
STATE_LAYOUT = struct.Struct("<IIiihhhhHhBBBBIIII")
PARAMS_LAYOUT = struct.Struct("<IIIII")
PARAMETER_KEYS = ("kp_left_q100", "ki_left_q100", "kp_right_q100", "ki_right_q100")
COMMAND_TYPES = {"hello": HELLO, "arm_pwm": ARM, "arm_speed": ARM,
                 "set_pwm": SET_PWM, "stop": STOP, "set_speed": SET_SPEED,
                 "read_parameters": GET_PARAMS, "apply_parameters": SET_PARAMS}
ACK_MESSAGES = ("MCU 已接受", "长度或参数值错误", "会话不匹配", "旧序号",
                "未使能或模式不符", "本地禁止", "已使能，不能修改参数",
                "PI 未配置", "命令已过期", "未知命令")
STOP_REASONS = ("启动 / 会话重建", "用户 STOP / 本地按键", "运动到期",
                "本地禁止", "接收 / 发送溢出", "使能空闲到期")


def crc16(data: bytes) -> int:
    value = 0xFFFF
    for byte in data:
        value ^= byte << 8
        for _ in range(8):
            value = ((value << 1) ^ 0x1021) & 0xFFFF if value & 0x8000 else (value << 1) & 0xFFFF
    return value


def encode_frame(kind: int, session: int, seq: int, payload: bytes = b"") -> bytes:
    if len(payload) > 64:
        raise ValueError("PROJECT_V1 payload 超过 64 字节")
    header = HEADER.pack(b"\xA5\x5A", 1, kind, len(payload), session, seq)
    return header + payload + struct.pack("<H", crc16(header[2:] + payload))


@dataclass(frozen=True)
class ProjectEvent:
    kind: int
    session: int
    seq: int
    values: tuple[int, ...]


class ProjectV1Adapter:
    protocol = PROJECT_V1
    command_capabilities = {"arm_pwm": "open_loop", "set_pwm": "open_loop",
                            "arm_speed": "motion", "set_speed": "motion",
                            "stop": "telemetry", "read_parameters": "parameter_read",
                            "apply_parameters": "parameter_write"}

    def __init__(self, source: str):
        self.source = source
        self.session = 0
        self.seq = 0
        self._buffer = bytearray()
        self._issues = deque(maxlen=128)
        self._events = deque(maxlen=128)
        self._partial_since = None
        self._last_state_tick = None
        self._last_state_seq = 0
        self.reset()

    def reset(self):
        # Stream loss must not reset sequence/session or revive cached commands.
        self._buffer.clear()
        self._issues.clear()
        self._events.clear()
        self._partial_since = None
        self._last_state_tick = None
        self._last_state_seq = 0
        self._counters = dict(bytes_received=0, frames_parsed=0, rejected_frames=0,
                              discarded_bytes=0, issues_dropped=0)

    @property
    def diagnostics(self):
        return {**self._counters, "buffered_bytes": len(self._buffer)}

    def _issue(self, message):
        if len(self._issues) == self._issues.maxlen:
            self._counters["issues_dropped"] += 1
        self._issues.append(message)

    def pop_issues(self):
        result = list(self._issues)
        self._issues.clear()
        return result

    def pop_events(self):
        result = list(self._events)
        self._events.clear()
        return result

    def begin_session(self):
        self.reset()
        self.session = secrets.randbelow(0xFFFFFFFF) + 1
        self.seq = 0
        return self.encode_command("hello")

    def encode_command(self, command, values=None):
        values = values or {}
        if command not in COMMAND_TYPES:
            raise ValueError("未定义的 PROJECT_V1 命令")
        if not self.session:
            raise ValueError("尚未建立 PROJECT_V1 会话")
        if self.seq == 0xFFFFFFFF:
            raise ValueError("序号已耗尽，请断开并创建新会话")
        if command in ("hello", "stop", "read_parameters"):
            payload = b""
        elif command in ("arm_pwm", "arm_speed"):
            payload = bytes((1 if command == "arm_pwm" else 2,))
        elif command == "apply_parameters":
            if set(values) != set(PARAMETER_KEYS):
                raise ValueError("必须同时提交左右轮 kp / ki 四项 q100 参数")
            coefficients = [values[key] for key in PARAMETER_KEYS]
            if any(isinstance(x, bool) or not isinstance(x, int) or not 0 <= x <= 2000000 for x in coefficients):
                raise ValueError("q100 参数必须为 0..2000000 的整数")
            payload = struct.pack("<IIII", *coefficients)
        else:
            try:
                left, right, duration, deadline = (values[key] for key in ("left", "right", "duration_ms", "deadline_tick"))
            except KeyError as exc:
                raise ValueError("运动命令缺少数值或绝对期限") from exc
            limit = 6000 if command == "set_pwm" else 300
            if any(isinstance(x, bool) or not isinstance(x, int) for x in (left, right, duration, deadline)):
                raise ValueError("运动命令字段必须为整数")
            if not (-limit <= left <= limit and -limit <= right <= limit and 1 <= duration <= 1000 and 0 <= deadline <= 0xFFFFFFFF):
                raise ValueError("运动值、时长或绝对期限越界")
            payload = struct.pack("<hhHI", left, right, duration, deadline)
        self.seq += 1
        return encode_frame(COMMAND_TYPES[command], self.session, self.seq, payload)

    def feed(self, chunk, received_monotonic=None, received_utc=None):
        if not isinstance(chunk, bytes):
            raise TypeError("chunk must be bytes")
        now = time.monotonic() if received_monotonic is None else received_monotonic
        utc = received_utc or datetime.now(timezone.utc).isoformat(timespec="milliseconds")
        self._counters["bytes_received"] += len(chunk)
        if self._buffer and self._partial_since is not None and now - self._partial_since > .1:
            self._counters["discarded_bytes"] += len(self._buffer)
            self._buffer.clear()
            self._partial_since = None
            self._issue("PROJECT_V1 半帧超过 100 ms，已丢弃并重新同步")
        samples = []
        # Process in small blocks; hostile input never expands the RX buffer.
        for offset in range(0, len(chunk), 64):
            self._buffer.extend(chunk[offset:offset + 64])
            while self._buffer:
                start = self._buffer.find(b"\xA5\x5A")
                if start < 0:
                    keep = 1 if self._buffer[-1] == 0xA5 else 0
                    self._counters["discarded_bytes"] += len(self._buffer) - keep
                    self._buffer[:] = self._buffer[-1:] if keep else b""
                    break
                if start:
                    self._counters["discarded_bytes"] += start
                    del self._buffer[:start]
                if len(self._buffer) < HEADER.size:
                    break
                _, version, kind, length, session, seq = HEADER.unpack_from(self._buffer)
                if version != 1 or length > 64:
                    self._counters["rejected_frames"] += 1
                    del self._buffer[0]
                    self._issue("PROJECT_V1 版本或长度错误")
                    continue
                total = HEADER.size + length + 2
                if len(self._buffer) < total:
                    break
                raw = bytes(self._buffer[:total])
                if crc16(raw[2:-2]) != struct.unpack_from("<H", raw, total - 2)[0]:
                    self._counters["rejected_frames"] += 1
                    del self._buffer[0]
                    self._issue("PROJECT_V1 CRC 错误，已丢弃")
                    continue
                del self._buffer[:total]
                if not self.session or session != self.session:
                    self._issue("忽略会话身份不匹配的 PROJECT_V1 回包")
                    continue
                payload = raw[HEADER.size:-2]
                layout = {CAPS: CAPS_LAYOUT, ACK: struct.Struct("<BB"), STATE: STATE_LAYOUT, PARAMS: PARAMS_LAYOUT}.get(kind)
                if layout is None or len(payload) != layout.size:
                    self._issue("PROJECT_V1 回包类型或长度错误")
                    continue
                fields = layout.unpack(payload)
                if kind == STATE:
                    tick, last_seq, enc_l, enc_r, speed_l, speed_r, pwm_l, pwm_r, mv, battery, mode, armed, reason, local, rx_drop, tx_drop, rev, reserved = fields
                    if last_seq > self.seq or mode > 2 or armed > 1 or local > 1 or reason > 5 or reserved:
                        self._issue("PROJECT_V1 STATE 身份或状态值错误")
                        continue
                    if ((self._last_state_tick is not None and not 0 < ((tick - self._last_state_tick) & 0xFFFFFFFF) < 0x80000000)
                            or last_seq < self._last_state_seq):
                        self._issue("忽略设备 tick / last_seq 倒退的 STATE")
                        continue
                    self._last_state_tick, self._last_state_seq = tick, last_seq
                    samples.append(TelemetrySample(now, utc, self.source, self.protocol,
                        abs(speed_l) / 1000, abs(speed_r) / 1000, battery,
                        quality=("battery_out_of_range",) if not 0 <= battery <= 100 else (),
                        raw_frame=raw, device_time_ms=tick, pwm_left=pwm_l, pwm_right=pwm_r,
                        encoder_left=enc_l, encoder_right=enc_r,
                        signed_left_speed_mps=speed_l / 1000, signed_right_speed_mps=speed_r / 1000,
                        battery_mv=mv, control_mode=mode, armed=bool(armed), stop_reason=reason,
                        local_enable=bool(local), rx_dropped=rx_drop, tx_dropped=tx_drop,
                        parameter_revision=rev, device_last_seq=last_seq, device_session=session))
                else:
                    if len(self._events) == self._events.maxlen:
                        self._issue("PROJECT_V1 回包事件缓存溢出")
                    self._events.append(ProjectEvent(kind, session, seq, fields))
                self._counters["frames_parsed"] += 1
            self._partial_since = now if self._buffer and self._partial_since is None else self._partial_since
            if not self._buffer:
                self._partial_since = None
        return samples
